# Site settings
title: Living in IT
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Experiences about coding, writing and IT-Stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  B3J4y

# Build settings
markdown: kramdown
